version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: yugmi-postgres-dev
    environment:
      POSTGRES_DB: construction_monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d construction_monitoring"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  app:
    build: .
    container_name: yugmi-backend-dev
    ports:
      - "3000:3000"
      - "9229:9229"  # Debug port
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=construction_monitoring
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/construction_monitoring
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
      - ./package.json:/app/package.json
    command: npm run dev
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: yugmi-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@yugmi.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_dev_data:
    driver: local
